### ISSUE TITLE
영업시스템 업무FLOW

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [Team5-be01-Final-Project/Main#13]
- 영업시스템 업무 FLOW 작성

<img src="https://github.com/Team5-be01-Final-Project/Main/assets/149128094/e3ce5f10-3dab-4e78-8260-770538eb3414">

**Comment by INAUGURATE-Ryong** [comment]
@parc02  민성님. FLOW 완성되면 Comment로 공유 해주세요~

**Comment by parc02** [comment]
- 업무 flow
![Image](https://github.com/Team5-be01-Final-Project/Main/assets/148880521/cf9ce1b9-938d-4e41-b0ac-6fd68fb5c9de)

---------------------------------------------------

![Image](https://github.com/Team5-be01-Final-Project/Main/assets/148880521/1c08587e-0c6c-4141-8d50-da5e89dfb4e1)
