### ISSUE TITLE
1차 멘토링 준비

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [Team5-be01-Final-Project/Main#9]
2024-03-05 PM07:00 시작

- [x] 프로젝트 기획서 초안 작성
- [x] 업무 FLOW작성
- [x] 요구사항정의서 작성
- [x] 화면설계서 작성

**Comment by INAUGURATE-Ryong** [comment]
1. 프로젝트 기획서 초안 : https://docs.google.com/document/d/1JutpuYJL_yCm8hQWI-VryxhG7xn5n237kbDja1depHw/edit

**Comment by INAUGURATE-Ryong** [comment]
- 2024-03-05(화) 멘토링 18시 50분 시작

**Comment by dhkdtld37** [comment]
1. 영업 사원에 대한 규모와 그 에 따른 나올 데이터를 미리 정하고, 그 규모에 따른 그래프나, 지도로  지점을 표현, 우수 사원이나 우수 지점 등 표현 방법을 설정하기 ( 전체적인 규모 우선 설정 )
2. 특정 주력 상품에 대한 정보 또한 제공 ( 기간, 목표치 )
3. 권한에 따른 분기 화면은 명확할 수록 좋음
4. 매입이나 매출 중 하나의 범위를 축소하여 축소한 만큼 상세한 기능에 집중
5. 본 수가 많아짐에 따라 분기 화면 또한 많아지니 범위를 미리 정할 것
6. 상품에 대한 상세한 분류 추가
7. 중복 방지를 위해 로그인 시 다른 곳에서 로그인 x, 기능x?
8. 매출에 있어서 영업 사원과 회사와의 비율?
9. DB의 경우 정규화같은 절차보다 실제 데이터 내용에 집중할 것
10. 기획안 내용들 상세한 설명 추가 필요
11. 관리자와 사원에 대한 명확한 목표 제시
12. 팀원 별 파트를 구분

7일 금요일 저녁에 미팅, 그 전까지 요구 사항 정의서 초안 작성 마칠 것
WBS는 멘토님과 가이드
